# Generated by Django 4.2.7 on 2023-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
